# Generated by Django 3.0.8 on 2020-07-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200721_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='poster_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
