# Generated by Django 3.0.8 on 2020-07-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='time',
            new_name='timestamp',
        ),
    ]
