# Generated by Django 3.0.8 on 2020-07-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200716_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_json',
            field=models.CharField(max_length=500),
        ),
    ]
